# Generated by Django 3.0.3 on 2020-02-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_total_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_received',
            field=models.IntegerField(default=0),
        ),
    ]
