# Generated by Django 3.0.3 on 2020-02-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood',
            old_name='type',
            new_name='bg_group',
        ),
        migrations.AddField(
            model_name='blood',
            name='unit_available',
            field=models.IntegerField(default=0),
        ),
    ]
